spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nisan4db
    username: yourusername
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
